### ISSUE TITLE
Duplicate declaration: Jenkins::Plugin[credentials] is already declared

### ISSUE THREAD

**Issue by FransUrbo** [jenkinsci/puppet-jenkins#680] opened 2016-11-23 14:25 UTC
I'm running with Puppet v3.8.5 and I get Subject when trying to apply my manifest (on my Ubuntu 16.04/LTS with dist puppet).

This manifest works:
```
class role_jenkins {
    $adm_pw = hiera('jenkins_admin_user', undef)

    package { 'openjdk-9-jdk-headless':
        ensure => installed,
    } ->

    class {'::jenkins':
        version      => latest,
        repo         => true,
        install_java => false,
        executors    => 1,
        user_hash => {
            'admin' => {
                'password' => "$adm_pw",
                'email'    => 'admin@domain.tld'
            }
        },
    }
}
```

But as soon as I add
```
plugin_hash => {
    <something,>
    'credentials' => {},
    <something>
}
```
I get Subj.

Obvious solution is not to enter `credentials` in the `plugin_hash` :). So either document this (simple solution) or filter out that when `plugin_hash` is processed (more complicated/time consuming solution). I'm good with either way, although the second would probably be best :)

**Comment by jhoblitt** [comment] 2016-11-23 19:23
Duplicate of #665

**Closed by jhoblitt** 2016-11-23 19:23 UTC
