### ISSUE TITLE
Unbuntu apt-get and plugins gives wrong version of jenkins

### ISSUE THREAD

**Issue by athingisathing** [jenkinsci/puppet-jenkins#461] opened 2016-01-12 17:05 UTC
So after a week of fighting with the code i realized that jenkins was installing at the wrong version when i use a plugin hash.

When installing jenkins on unbuntu 12 using this code it works fine, also when you add in the plugins one by one it works, but when you switch to hiera and use a plugin hash the wrong version of jira gets installed.  I new jira did not look right but it took me a week of focusing on the dam plugins not working to give up and start with the basics lol my bad!!!!!

if you add this to debian.pp file after the source it fixed it for me. Tbis is a common fix for debian it forces the apt-update at the correct location.
 ->
    Exec['apt_update'] -> Package['jenkins']

**Comment by jhoblitt** [comment] 2016-02-08 17:34
Duplicate of #453

**Closed by jhoblitt** 2016-02-08 17:34 UTC
Labels: duplicate
