### ISSUE TITLE
PR #467 broke puppet_cli_helper

### ISSUE THREAD

**Issue by rvincentatprokarmadotcom** [jenkinsci/puppet-jenkins#477] opened 2016-01-22 20:26 UTC
[PR 467](https://github.com/jenkinsci/puppet-jenkins/pull/467) broke Jenkins for me.  I'm getting the following error while trying to call the create_or_update_user function as documented in the [README](https://github.com/jenkinsci/puppet-jenkins/blob/master/README.md#cli-helper):

```
sudo -u jenkins java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://127.0.0.1:8080 groovy /usr/lib/jenkins/puppet_helper.groovy create_or_update_user jenkins vti-cicd-team
@verizon.com '' Jenkins AAAAB3NzaC1yc2EAAAADAQABAAABAQCsfx5mDlmYfB/c5TXxcf3chDexd9IwbKsqBmFXTgK/uibehGKixnXnJtoVjvxSoTEtIp+hnMIScbXAXsDM/RLzZ1dCmnBOEnj6Oyd50jZAz4oN0A3ITeS9/J
/jeBoHOFeA12clOZmhmj0tIR5I5vTZo+kRNX2NtC257V12StXMFScnMcN9CR+AARb3gg0skCC/AM37AbLYbdiOR9iYQ2SygHsQdzibzzhhIfZhttXYBLw8y597GI43fncVtGVbBEhYzX/yf/T3qhX1eYc/3IUQNfECLOHlJS7HJFod
QQ5ZHxRCzDfayyXUIJdl6qnQuBWyFqtb3aUYONmoN4VoVqNb
[WARN] Failed to authenticate with your SSH keys. Proceeding as anonymous
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
RemoteClass: 668: unable to resolve class FileCredentialsImpl
 @ line 668, column 16.
           cred = new FileCredentialsImpl(
                  ^

1 error

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:302)
        at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:861)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:550)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:499)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:302)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:281)
        at groovy.lang.GroovyShell.parseClass(GroovyShell.java:731)
        at groovy.lang.GroovyShell.run(GroovyShell.java:516)
        at hudson.cli.GroovyCommand.run(GroovyCommand.java:86)
        at hudson.cli.CLICommand.main(CLICommand.java:237)
        at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:608)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:583)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:542)
        at hudson.remoting.UserRequest.perform(UserRequest.java:120)
        at hudson.remoting.UserRequest.perform(UserRequest.java:48)
        at hudson.remoting.Request$2.run(Request.java:326)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
        at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:63)
        at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
        at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jhoblitt** [comment] 2016-01-22 22:13
Duplicate of #476

**Closed by jhoblitt** 2016-01-22 22:13 UTC
