### ISSUE TITLE
Some plugins not updating

### ISSUE THREAD

**Issue by robinbowes** [jenkinsci/puppet-jenkins#118] opened 2014-04-03 12:53 UTC
Hi,

I'm using the 1.0.1 release of this module with PE 3.1.3 on RHEL6.

I'm using the plugin code like this:

```
create_resources(jenkins::plugin, hiera('jenkins_plugins', {}))
```

Where "jenkins_plugins" is a hash structure containing something like:
```
jenkins_plugins:
  'multiple-scms':
    version: '0.3'
  'token-macro':
    version: '1.10'
...
```

I'm finding that some plugins do not update - it seems to be those that are distributed as plugin_name.hpi, eg. credentials.

When puppet runs, it says it installed the plugin:

```
Notice: /Stage[main]/Profile_jenkins/Jenkins::Plugin[credentials]/Exec[download-credentials]/returns: executed successfully
Notice: /Stage[main]/Profile_jenkins/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/owner: owner changed 'root' to 'jenkins'
Notice: /Stage[main]/Profile_jenkins/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/mode: mode changed '0600' to '0644'
Info: /Stage[main]/Profile_jenkins/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]: Scheduling refresh of Service[jenkins]
Info: /Stage[main]/Profile_jenkins/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]: Scheduling refresh of Service[jenkins]
```

However, Update Centre still shows the old version and the same code runs again next time puppet runs.

Any ideas?

R.

**Comment by jhoblitt** [comment] 2015-10-11 22:11
I believe this issue should be resolved by #389 so I'm going to close this issue.  Please reopen it if the problem is reproducible with the current master.

**Closed by jhoblitt** 2015-10-11 22:11 UTC
Labels: bug, feedback-needed
