### ISSUE TITLE
Keeps want to recreate users on every run

### ISSUE THREAD

**Issue by FransUrbo** [jenkinsci/puppet-jenkins#682] opened 2016-11-23 14:40 UTC
Every time I run puppet, I get:

```
Notice: /Stage[main]/Jenkins::Users/Jenkins::User[admin]/Jenkins::Cli::Exec[create-jenkins-user-admin]/Exec[create-jenkins-user-admin]/returns: executed successfully
Info: /Stage[main]/Jenkins::Users/Jenkins::User[admin]/Jenkins::Cli::Exec[create-jenkins-user-admin]/Exec[create-jenkins-user-admin]: Scheduling refresh of Class[Jenkins::Cli::Reload]
Info: Class[Jenkins::Cli::Reload]: Scheduling refresh of Exec[reload-jenkins]
```

**Comment by jhoblitt** [comment] 2016-11-23 19:29
Looks like a duplicate of  #684

**Closed by jhoblitt** 2016-11-23 19:29 UTC

**Comment by FransUrbo** [comment] 2016-11-23 21:35
I don't think this is a duplicate. ONCE I could get #684 to succeed, but I still got this [the 'try to create on every run'].
